name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-docker@v2
      - name: Build Docker image
        run: docker build -t cml-py3 .
      - name: Install dependencies
        run: |
          docker run --rm -v $PWD:/app -w /app cml-py3 pip install -r requirements.txt
      - name: Train model
        run: |
          docker run --rm -v $PWD:/app -w /app cml-py3 python train.py
      - name: Generate report
        run: |
          echo "## Model metrics" > report.md
          type metrics.txt >> report.md
          echo "## Data viz" >> report.md
          docker run --rm -v $PWD:/app -w /app cml-py3 cml-publish feature_importance.png --md >> report.md
          docker run --rm -v $PWD:/app -w /app cml-py3 cml-publish residuals.png --md >> report.md
          docker run --rm -v $PWD:/app -w /app cml-py3 cml-send-comment report.md
