name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Train model
        run: |
          python train.py
      - name: Generate report
        run: |
          echo "## model metrics" > report.md
          type metrics.txt >> report.md
          echo "## Data Viz" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          cnl-send-comment report.md
